develop:
  url: "http://27.254.66.181:8080/SMLJavaRESTService/v3/api/product"
  GUID: 'smix'
  configFileName: 'SMLConfigData.xml'
  databaseName: 'data1'
  provider: data

prod:
  url: "http://27.254.66.181:8080/SMLJavaRESTService/v3/api/product"
  GUID: 'smix'
  configFileName: 'SMLConfigData.xml'
  databaseName: 'data1'
  provider: data

